# Generated by Django 5.1.4 on 2024-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=10)),
                ('pepperoni', models.BooleanField(default=False)),
                ('extra_cheese', models.BooleanField(default=False)),
                ('bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
